#!/bin/bash

if [[ ! $# = 1 || ! $1 = [1-8] ]] ; then echo "This script must be run with the group number as parameter." ; false ; exit ; fi ;

curl -i --location --request POST "https://ci.mines-stetienne.fr/simu$1/cupProvider/actions/order" --header 'Content-Type: application/json' --data-raw '25';
curl -i --location --request POST "https://ci.mines-stetienne.fr/simu$1/storageRack/actions/pressEmergencyStop";
curl -i --location --request POST "https://ci.mines-stetienne.fr/simu$1/fillingWorkshop/actions/pressEmergencyStop";
#curl --location --request POST "https://ci.mines-stetienne.fr/simu$1/robotArm/actions/pressEmergencyStop";
curl -i --location --request POST "https://ci.mines-stetienne.fr/simu$1/packagingWorkshop/actions/pressEmergencyStop";
curl -i --location --request POST "https://ci.mines-stetienne.fr/simu$1/cupProvider/actions/orderPackages" --header 'Content-Type: application/json' --data-raw '5';
