#!/bin/bash

if [[ ! $# = 1 || ! $1 = [1-8] ]] ; then echo "This script must be run with the group number as parameter." ; false ; exit ; fi ;

echo "Calling factory.reset..."; echo;
curl -i --user "simu$1:simu$1" --location --request POST "https://ci.mines-stetienne.fr/simu/factory/actions/reset";
echo "Reset done."